### ISSUE TITLE
Exception while trying to obtain process id from Windows 7

### ISSUE THREAD

**Issue by vijaygopal** [zeroturnaround/zt-process-killer#12]
I was writing a program to invoke a process and return the PID using PIDUtils. But when I tried to obtain the PID I received the below exception

Caused by: java.lang.NoClassDefFoundError: org/zeroturnaround/process/win/Kernel32
	at org.zeroturnaround.process.PidUtil.getPidfromHandle(PidUtil.java:145)
	at org.zeroturnaround.process.PidUtil.getPidfromWin32Process(PidUtil.java:135)
	at org.zeroturnaround.process.PidUtil.doGetPid(PidUtil.java:102)
	at org.zeroturnaround.process.PidUtil.getPid(PidUtil.java:90)
	at org.me.processexecutor.ProcessInvoker.call(MNXZeroTurnaround.java:53)
	at org.me.processexecutor.ProcessInvoker.call(MNXZeroTurnaround.java:1)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by reinra** [comment]
Could you try it with a sandbox application to determine that it's not related to your application setup?
