### ISSUE TITLE
Add support for Java 12/13

### ISSUE THREAD

**Issue by theangrydev** [zeroturnaround/zt-process-killer#17]
On OpenJDK 12/13 I see this:
```
Exception in thread "main" java.lang.IllegalStateException: Could not detect PID form Process[pid=26, exitValue="not exited"]
	at org.zeroturnaround.process.PidUtil.doGetPid(PidUtil.java:117)
	at org.zeroturnaround.process.PidUtil.getPid(PidUtil.java:97)
Caused by: java.lang.NoSuchFieldException: handle
	at java.base/java.lang.Class.getDeclaredField(Class.java:2417)
	at org.zeroturnaround.process.PidUtil.getHandle(PidUtil.java:150)
	at org.zeroturnaround.process.PidUtil.getPidFromWin32Process(PidUtil.java:146)
	at org.zeroturnaround.process.PidUtil.doGetPid(PidUtil.java:113)
	... 4 more
```

**Comment by nemecec** [comment]
Added JDK 12 to Travis in PR #19. The failure is also visible there.

**Comment by nemecec** [comment]
Issue is fixed in master with commit c3a927f30aa752de6e90f64f7c9d92403b0aafb2. @theangrydev, can you try and see if it works for you also?

**Comment by theangrydev** [comment]
@nemecec seems to work for me

**Comment by mdaloia** [comment]
It seems that this issue could be closed. 
As [mentioned above](https://github.com/zeroturnaround/zt-process-killer/issues/17#issuecomment-483561339) it was fixed with https://github.com/zeroturnaround/zt-process-killer/commit/c3a927f30aa752de6e90f64f7c9d92403b0aafb2 which is included in the [version 1.10](https://github.com/zeroturnaround/zt-process-killer/releases/tag/zt-process-killer-1.10)
