### ISSUE TITLE
need to bump to latest jna and zt-exec

### ISSUE THREAD

**Issue by nddipiazza** [zeroturnaround/zt-process-killer#22]
issues on win2016 server after latest patches:

```
java.lang.UnsatisfiedLinkError: C:\Users\Administrator\AppData\Local\Temp\jna-146731693\jna5340145331185949059.dll: Can't find dependent librariesat java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_265]at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934) ~[?:1.8.0_265]at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817) ~[?:1.8.0_265]at java.lang.Runtime.load0(Runtime.java:810) ~[?:1.8.0_265]at java.lang.System.load(System.java:1088) ~[?:1.8.0_265]at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:851) ~[lucidworks-agent.jar:?]at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826) ~[lucidworks-agent.jar:?]at com.sun.jna.Native.<clinit>(Native.java:140) ~[lucidworks-agent.jar:?]at com.sun.jna.Pointer.<clinit>(Pointer.java:41) ~[lucidworks-agent.jar:?]at com.sun.jna.PointerType.<init>(PointerType.java:25) ~[lucidworks-agent.jar:?]at org.zeroturnaround.process.win.W32API$HANDLE.<init>(W32API.java:49) ~[lucidworks-agent.jar:?]at org.zeroturnaround.process.win.W32API$3.<init>(W32API.java:59) ~[lucidworks-agent.jar:?]at org.zeroturnaround.process.win.W32API.<clinit>(W32API.java:59) ~[lucidworks-agent.jar:?]at org.zeroturnaround.process.win.Kernel32.<clinit>(Kernel32.java:5) ~[lucidworks-agent.jar:?]at org.zeroturnaround.process.PidUtil.getPidFromHandle(PidUtil.java:156) ~[lucidworks-agent.jar:?]at org.zeroturnaround.process.PidUtil.getPidFromWin32Process(PidUtil.java:146) ~[lucidworks-agent.jar:?]at org.zeroturnaround.process.PidUtil.doGetPid(PidUtil.java:113) ~[lucidworks-agent.jar:?]at org.zeroturnaround.process.PidUtil.getPid(PidUtil.java:97) ~[lucidworks-agent.jar:?]
```

**Comment by mdaloia** [comment]
It seems that this issue could be closed. 
It was addressed in https://github.com/zeroturnaround/zt-process-killer/pull/23 but not currently released.

**Comment by nemecec** [comment]
Fixed — both bumps have landed in 1.12.0:

| Dependency | 1.10 (what this was reported against) | 1.12.0 |
| --- | --- | --- |
| `jna` | 4.2.2 | 5.19.1 |
| `zt-exec` | 1.7 | 1.13.0 |

Both are the current latest releases on Maven Central.

On the underlying `UnsatisfiedLinkError`: `Can't find dependent libraries` when loading the extracted `jna*.dll` is the signature of the JNA 4.x native library being dynamically linked against a Visual C++ runtime that is not present on the machine. JNA 5.x links that statically, so the bump is very likely to resolve it — though that has not been reconfirmed on Windows Server 2016 specifically.

Closing as fixed. If it still reproduces on 1.12.0, please reopen with the stack trace and the JNA version actually resolved on your classpath.

Dependency updates are now handled by Dependabot on a weekly schedule, so these versions should not fall this far behind again.
