### ISSUE TITLE
UnsatisfiedLinkError on Apple Silicon Macs

### ISSUE THREAD

**Issue by jongyu** [zeroturnaround/zt-process-killer#28]
Description:
I encountered an UnsatisfiedLinkError while using the zt-process-killer library on my Apple Silicon Mac computer. The error occurs when trying to load the JNA native library from the temporary cache directory. The error message indicates a compatibility issue with the architecture, specifically that the library is built for 'arm64' architecture, but my system has 'i386' and 'x86_64' architectures. The issue is not present on other systems.

Steps to Reproduce:

Install and run the application on an Apple Silicon Mac computer.
Perform actions that trigger the usage of the zt-process-killer library.
Observe the UnsatisfiedLinkError in the application log.
Expected Behavior:
The zt-process-killer library should work correctly on Apple Silicon Macs and load the appropriate native library.

Actual Behavior:
The UnsatisfiedLinkError occurs when trying to load the JNA native library, preventing the library from functioning as expected on Apple Silicon Macs.

Environment:

Operating System: macOS (Apple Silicon)
Java Version: [17.0.6]
Library Version: [zt-process-killer:1.10]
Error Stack Trace:

```java
10:46:43.374 [AWT-EventQueue-0] DEBUG org.zeroturnaround.process.PidUtil -- Found PID for Process[pid=93803, exitValue="not exited"]: 93803
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: /Users/test/Library/Caches/JNA/temp/jna7753793422651422146.tmp: dlopen(/Users/test/Library/Caches/JNA/temp/jna7753793422651422146.tmp, 0x0001): tried: '/Users/test/Library/Caches/JNA/temp/jna7753793422651422146.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/test/Library/Caches/JNA/temp/jna7753793422651422146.tmp' (no such file), '/Users/test/Library/Caches/JNA/temp/jna7753793422651422146.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64'))
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at org.zeroturnaround.process.unix.LibC.<clinit>(LibC.java:8)
	at org.zeroturnaround.process.UnixProcess.kill(UnixProcess.java:46)
	at org.zeroturnaround.process.UnixProcess.destroy(UnixProcess.java:34)
	at org.zeroturnaround.process.AbstractProcess.destroyGracefully(AbstractProcess.java:91)
	at org.zeroturnaround.process.AbstractProcess.destroyGracefully(AbstractProcess.java:16)
	at org.zeroturnaround.process.ProcessUtil.destroyGracefullyAndWait(ProcessUtil.java:66)
	at org.zeroturnaround.process.ProcessUtil.destroyGracefullyOrForcefullyAndWait(ProcessUtil.java:130)
	at IOSMonkey.stop(Main.kt:380)
	at MainKt$DeviceItem$1.invoke(Main.kt:397)
	at MainKt$DeviceItem$1.invoke(Main.kt:394)
	at MainKt$ConfirmStopDialog$2$1$1.invoke(Main.kt:452)
	at MainKt$ConfirmStopDialog$2$1$1.invoke(Main.kt:452)
```
Additional Information:
I have verified that the zt-process-killer library works fine on non-Apple Silicon Macs with 'i386' and 'x86_64' architectures.

Possible Solution:
Investigate the zt-process-killer library and JNA dependencies to ensure they are built with Apple Silicon M1 chip support ('arm64' architecture). Additionally, consider checking the JNA version compatibility and using the latest version that supports Apple Silicon Macs.

Thank you for your attention to this issue, and I look forward to a resolution that would make the zt-process-killer library compatible with Apple Silicon Macs.

**Comment by toomasr** [comment]
I see from [java-native-access/jna changelog](https://github.com/java-native-access/jna/blob/master/CHANGES.md) that there have been changes addressing maybe similar issues (for example, #1323 which is a crash on m1 but still). The zt-process-killer uses JNA library version 5.7 and fixes have been introduced in later versions.

I also tested it on my machine and sure I could see the UnsatisfiedLinkError with the zt-process-killer 1.10 and it disappeared after upgrading the JNA version.

I've released zt-process-killer 1.11 with the latest jna dependency. Should be visible on maven central shortly. I presume it will fix your issue as well.
